services:
  tfg-api-v2:
    build: .
    container_name: tfg-api-v2
    ports:
      - "8001:8000"
    restart: unless-stopped
    environment:
      DATABASE_URL: "postgresql://buffas:Torero1234.@187.77.175.78:32772/tfg_emails"
      GEMINI_API_KEY: "AIzaSyDj0Mj-wik3kdBge_zNYsJuLRJTTOzeZvs"
      GEMINI_MODEL: "gemini-2.5-flash-lite"
      DEFAULT_ENGINE: "gemini"
      CONFIDENCE_THRESHOLD: "0.6"
      API_KEY: "tfg_diego"